# Model architecture configuration for multimodal TimesFM

# Base TimesFM 2.5 configuration
timesfm:
  # ForecastConfig parameters
  max_context: 1024
  max_horizon: 256
  normalize_inputs: true
  per_core_batch_size: 32

  # TimesFM 2.5 model parameters (matches TimesFM_2p5_200M_Definition)
  context_limit: 16384
  input_patch_len: 32
  output_patch_len: 128
  output_quantile_len: 1024
  num_layers: 20 # Updated for TimesFM 2.5
  num_heads: 16
  model_dims: 1280
  quantiles: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  decode_index: 5

# Text encoder configuration
text_encoder:
  text_encoder_type: "english" # "english" or "japanese"
