# Model architecture configuration for multimodal TimesFM

# Base TimesFM configuration
timesfm:
  # TimesFmHparams
  context_len: 128
  horizon_len: 128
  input_patch_len: 32
  output_patch_len: 128
  num_layers: 50
  num_heads: 16
  model_dims: 1280
  per_core_batch_size: 32
  backend: "gpu"
  quantiles: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  use_positional_embedding: true
  point_forecast_mode: "median"

  # TimesFMConfig
  num_kv_heads: 16
  rms_norm_eps: 1e-6
  pad_val: 1123581321.0
  tolerance: 1e-6
  dtype: "bfloat32"

# Text encoder configuration
text_encoder:
  text_encoder_type: "english"  # "english" or "japanese"
