# Training configuration for multimodal TimesFM on Time-MMD dataset

# Hardware configuration
hardware:
  device: null # Auto-detect: cuda, mps, or cpu

# Data configuration
data:
  data_path: "data/Time-MMD"
  domains: ["Environment"]
  split_ratio: 0.8 # Train/validation split
  patch_len: 32
  context_len: 128
  horizon_len: 32

# Training configuration
train:
  batch_size: 8
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  learning_rate: 1e-4
  weight_decay: 0.01
  num_epochs: 50
  wandb_run_name: "multimodal-timesfm-time-mmd"

# Logging configuration
log:
  save_dir: "logs"
  experiment_name: "multimodal_timesfm_time_mmd"

# Checkpoint configuration
checkpoint:
  save_dir: "checkpoints"
  save_frequency: 5 # Save every 5 epochs
